SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE `about` (
  `content` text NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `about` (`content`) VALUES
('<p><b><i>This content comes from the <u>ABOUT</u> table in the database.</i></b></p>\r\n\r\n<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vel metus arcu. Quisque efficitur tincidunt erat. Donec suscipit ante eu nisi tincidunt, sed pulvinar metus finibus. Pellentesque volutpat quam nec blandit mollis. Nulla id diam in nulla maximus rhoncus. Pellentesque non magna sed orci viverra bibendum sodales eu erat. In sollicitudin sapien ut enim tempor fermentum. Integer venenatis id metus a accumsan. Donec ut congue augue, vel sagittis sapien. Fusce venenatis nisl elit, ut venenatis ante pretium nec. Donec pretium ut leo ut faucibus.</p>\r\n\r\n<p>Aenean consequat viverra venenatis. Cras vitae congue tellus, in sodales magna. Morbi elementum sed tellus quis varius. Quisque feugiat finibus pharetra. In pretium eu velit ut pretium. Pellentesque aliquam eu metus non porttitor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed egestas lacus quis dapibus placerat. Nullam et mollis justo. Duis mattis bibendum ultricies. Maecenas eget ex rhoncus, facilisis nulla ullamcorper, tempus arcu. Aenean cursus id sapien nec dignissim. Praesent vulputate euismod commodo. Mauris fermentum, turpis ut ultrices luctus, risus sapien pharetra augue, eu elementum dui justo quis nisl. Proin sagittis erat ac commodo consequat.</p>\r\n\r\n<p>Vestibulum viverra justo magna, sed dignissim est aliquam at. Phasellus in mi vel risus tincidunt bibendum nec quis libero. Integer id tortor dolor. Suspendisse consectetur id metus eget molestie. Cras sagittis, sapien ut pharetra mattis, nisl augue pharetra leo, eu consectetur orci metus vitae arcu. Integer in auctor orci. Mauris sit amet lacus eu eros volutpat gravida et a nulla. Aenean ex sem, fermentum ac tortor vitae, finibus tincidunt mi. Cras fringilla, eros non euismod scelerisque, lorem purus molestie ante, non dignissim metus orci ac arcu. Mauris ut tempus ex. Sed est sapien, finibus ut cursus vitae, porta vulputate enim.</p>');

CREATE TABLE `comments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `comment` text NOT NULL,
  `datetime` datetime NOT NULL,
  `active` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `comments` (`id`, `name`, `comment`, `datetime`, `active`) VALUES
(1, 'Ronald L Allman', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vel metus arcu. Quisque efficitur tincidunt erat. Donec suscipit ante eu nisi tincidunt, sed pulvinar metus finibus. Pellentesque volutpat quam nec blandit mollis. Nulla id diam in nulla maximus rhoncus. Pellentesque non magna sed orci viverra bibendum sodales eu erat.', '2022-06-17 12:32:41', 1),
(2, 'Cheryl J Gardner', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vel metus arcu. Quisque efficitur tincidunt erat. Donec suscipit ante eu nisi tincidunt, sed pulvinar metus finibus. Pellentesque volutpat quam nec blandit mollis. Nulla id diam in nulla maximus rhoncus. Pellentesque non magna sed orci viverra bibendum sodales eu erat.', '2022-06-21 14:45:50', 1),
(3, 'Charles A Linker', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vel metus arcu. Quisque efficitur tincidunt erat. Donec suscipit ante eu nisi tincidunt, sed pulvinar metus finibus. Pellentesque volutpat quam nec blandit mollis. Nulla id diam in nulla maximus rhoncus. Pellentesque non magna sed orci viverra bibendum sodales eu erat.', '2022-06-21 17:33:05', 1),
(4, 'Frank Sloan', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vel metus arcu. Quisque efficitur tincidunt erat. Donec suscipit ante eu nisi tincidunt, sed pulvinar metus finibus. Pellentesque volutpat quam nec blandit mollis. Nulla id diam in nulla maximus rhoncus. Pellentesque non magna sed orci viverra bibendum sodales eu erat.', '2022-06-27 10:47:22', 1),
(5, 'Amy Smith', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vel metus arcu. Quisque efficitur tincidunt erat. Donec suscipit ante eu nisi tincidunt, sed pulvinar metus finibus. Pellentesque volutpat quam nec blandit mollis. Nulla id diam in nulla maximus rhoncus. Pellentesque non magna sed orci viverra bibendum sodales eu erat.', '2022-07-03 21:17:39', 1),
(6, 'Leila J Funk', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vel metus arcu. Quisque efficitur tincidunt erat. Donec suscipit ante eu nisi tincidunt, sed pulvinar metus finibus. Pellentesque volutpat quam nec blandit mollis. Nulla id diam in nulla maximus rhoncus. Pellentesque non magna sed orci viverra bibendum sodales eu erat.', '2022-07-15 16:19:52', 1);

CREATE TABLE `home` (
  `section1` text NOT NULL,
  `section2` text NOT NULL,
  `section3` text NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `home` (`section1`, `section2`, `section3`) VALUES
('<p><b><i>This content comes from the <u>MAIN</u> table in the database.</i></b></p>\r\n\r\n<p><b>Section 1:</b> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce bibendum commodo diam id porttitor. Suspendisse condimentum mattis erat eu consectetur. Cras faucibus vitae purus sit amet commodo. Morbi aliquet luctus justo, pulvinar egestas ex viverra blandit. Suspendisse nec tincidunt elit. Suspendisse ac felis vitae augue ullamcorper bibendum a tincidunt ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras placerat et lectus ut laoreet. Morbi aliquet, risus at hendrerit lacinia, nunc urna aliquam purus, id condimentum sem orci quis leo. Ut quis dictum est, vehicula pulvinar ligula. Nam nec nisi ac justo luctus pretium. Etiam tincidunt urna et elit lobortis vehicula. Nunc consequat, lorem ac condimentum faucibus, ligula dui scelerisque odio, id lacinia purus sem nec lectus. Maecenas non auctor eros. Fusce pulvinar lectus sit amet eros dictum, ut efficitur purus facilisis. Integer a libero vitae libero pellentesque maximus vel sed justo.</p>\r\n\r\n\r\n\r\n', '<p><b>Section 2:</b> Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris mollis est nec eleifend sollicitudin. Fusce consequat, lorem id maximus dictum, ipsum sapien cursus ipsum, eu efficitur tortor felis non enim. Ut pharetra dui facilisis dui suscipit, quis fermentum sem pulvinar. Aliquam rutrum dictum eleifend. Vestibulum et metus lacus. Sed sodales, dui eleifend accumsan ultrices, odio mauris euismod velit, luctus feugiat sem ex et libero. Aliquam mattis, nisi volutpat tristique finibus, tellus leo blandit nulla, sed feugiat quam diam at urna. In efficitur, augue vitae dictum accumsan, mi erat placerat mi, vulputate ullamcorper purus massa nec lorem. Phasellus velit elit, laoreet sit amet felis scelerisque, hendrerit blandit lectus. Sed in lectus convallis, egestas nulla sit amet, fermentum erat. Fusce sodales non lacus eu euismod. Ut rutrum tempor ligula, sit amet finibus arcu convallis nec. Cras nibh massa, venenatis ut tristique vitae, vestibulum sed nisl. Vestibulum venenatis nulla quis ligula ultrices, et commodo est fermentum.</p>', '<p><b>Section 3:</b> Ut purus odio, posuere eu suscipit venenatis, imperdiet vel magna. Vivamus a sem id neque luctus ultricies eu eu mi. Maecenas convallis tempor ex in ultricies. Phasellus sed accumsan augue, eget tristique quam. Maecenas ut est arcu. Cras velit urna, aliquam sed nibh a, interdum vehicula neque. Suspendisse potenti. Aliquam laoreet ultrices sem a volutpat. Vivamus tortor elit, euismod et mattis vel, tempor sollicitudin erat. Suspendisse in pharetra sem. Pellentesque consequat dapibus leo sit amet congue. In ornare eu diam eu vestibulum.</p>');

CREATE TABLE `services` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(250) NOT NULL,
  `description` text NOT NULL,
  `image` varchar(250) NOT NULL,
  `view` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `services` (`id`, `title`, `description`, `image`, `view`) VALUES
(1, 'Service Title 1', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vel metus arcu. Quisque efficitur tincidunt erat. Donec suscipit ante eu nisi tincidunt, sed pulvinar metus finibus. Pellentesque volutpat quam nec blandit mollis. Nulla id diam in nulla maximus rhoncus. Pellentesque non magna sed orci viverra bibendum sodales eu erat. In sollicitudin sapien ut enim tempor fermentum. Integer venenatis id metus a accumsan. Donec ut congue augue, vel sagittis sapien. Fusce venenatis nisl elit, ut venenatis ante pretium nec. Donec pretium ut leo ut faucibus.</p>\r\n\r\n<p>Aenean consequat viverra venenatis. Cras vitae congue tellus, in sodales magna. Morbi elementum sed tellus quis varius. Quisque feugiat finibus pharetra. In pretium eu velit ut pretium. Pellentesque aliquam eu metus non porttitor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed egestas lacus quis dapibus placerat. Nullam et mollis justo. Duis mattis bibendum ultricies. Maecenas eget ex rhoncus, facilisis nulla ullamcorper, tempus arcu. Aenean cursus id sapien nec dignissim. Praesent vulputate euismod commodo. Mauris fermentum, turpis ut ultrices luctus, risus sapien pharetra augue, eu elementum dui justo quis nisl. Proin sagittis erat ac commodo consequat.</p>\r\n\r\n<p>Vestibulum viverra justo magna, sed dignissim est aliquam at. Phasellus in mi vel risus tincidunt bibendum nec quis libero. Integer id tortor dolor. Suspendisse consectetur id metus eget molestie. Cras sagittis, sapien ut pharetra mattis, nisl augue pharetra leo, eu consectetur orci metus vitae arcu. Integer in auctor orci. Mauris sit amet lacus eu eros volutpat gravida et a nulla. Aenean ex sem, fermentum ac tortor vitae, finibus tincidunt mi. Cras fringilla, eros non euismod scelerisque, lorem purus molestie ante, non dignissim metus orci ac arcu. Mauris ut tempus ex. Sed est sapien, finibus ut cursus vitae, porta vulputate enim.</p>', 'Public/img/services/service1.jpg', 8),
(2, 'Service Title 2', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vel metus arcu. Quisque efficitur tincidunt erat. Donec suscipit ante eu nisi tincidunt, sed pulvinar metus finibus. Pellentesque volutpat quam nec blandit mollis. Nulla id diam in nulla maximus rhoncus. Pellentesque non magna sed orci viverra bibendum sodales eu erat. In sollicitudin sapien ut enim tempor fermentum. Integer venenatis id metus a accumsan. Donec ut congue augue, vel sagittis sapien. Fusce venenatis nisl elit, ut venenatis ante pretium nec. Donec pretium ut leo ut faucibus.</p>\r\n\r\n<p>Aenean consequat viverra venenatis. Cras vitae congue tellus, in sodales magna. Morbi elementum sed tellus quis varius. Quisque feugiat finibus pharetra. In pretium eu velit ut pretium. Pellentesque aliquam eu metus non porttitor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed egestas lacus quis dapibus placerat. Nullam et mollis justo. Duis mattis bibendum ultricies. Maecenas eget ex rhoncus, facilisis nulla ullamcorper, tempus arcu. Aenean cursus id sapien nec dignissim. Praesent vulputate euismod commodo. Mauris fermentum, turpis ut ultrices luctus, risus sapien pharetra augue, eu elementum dui justo quis nisl. Proin sagittis erat ac commodo consequat.</p>\r\n\r\n<p>Vestibulum viverra justo magna, sed dignissim est aliquam at. Phasellus in mi vel risus tincidunt bibendum nec quis libero. Integer id tortor dolor. Suspendisse consectetur id metus eget molestie. Cras sagittis, sapien ut pharetra mattis, nisl augue pharetra leo, eu consectetur orci metus vitae arcu. Integer in auctor orci. Mauris sit amet lacus eu eros volutpat gravida et a nulla. Aenean ex sem, fermentum ac tortor vitae, finibus tincidunt mi. Cras fringilla, eros non euismod scelerisque, lorem purus molestie ante, non dignissim metus orci ac arcu. Mauris ut tempus ex. Sed est sapien, finibus ut cursus vitae, porta vulputate enim.</p>', 'Public/img/services/service2.jpg', 19),
(3, 'Service Title 3', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vel metus arcu. Quisque efficitur tincidunt erat. Donec suscipit ante eu nisi tincidunt, sed pulvinar metus finibus. Pellentesque volutpat quam nec blandit mollis. Nulla id diam in nulla maximus rhoncus. Pellentesque non magna sed orci viverra bibendum sodales eu erat. In sollicitudin sapien ut enim tempor fermentum. Integer venenatis id metus a accumsan. Donec ut congue augue, vel sagittis sapien. Fusce venenatis nisl elit, ut venenatis ante pretium nec. Donec pretium ut leo ut faucibus.</p>\r\n\r\n<p>Aenean consequat viverra venenatis. Cras vitae congue tellus, in sodales magna. Morbi elementum sed tellus quis varius. Quisque feugiat finibus pharetra. In pretium eu velit ut pretium. Pellentesque aliquam eu metus non porttitor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed egestas lacus quis dapibus placerat. Nullam et mollis justo. Duis mattis bibendum ultricies. Maecenas eget ex rhoncus, facilisis nulla ullamcorper, tempus arcu. Aenean cursus id sapien nec dignissim. Praesent vulputate euismod commodo. Mauris fermentum, turpis ut ultrices luctus, risus sapien pharetra augue, eu elementum dui justo quis nisl. Proin sagittis erat ac commodo consequat.</p>\r\n\r\n<p>Vestibulum viverra justo magna, sed dignissim est aliquam at. Phasellus in mi vel risus tincidunt bibendum nec quis libero. Integer id tortor dolor. Suspendisse consectetur id metus eget molestie. Cras sagittis, sapien ut pharetra mattis, nisl augue pharetra leo, eu consectetur orci metus vitae arcu. Integer in auctor orci. Mauris sit amet lacus eu eros volutpat gravida et a nulla. Aenean ex sem, fermentum ac tortor vitae, finibus tincidunt mi. Cras fringilla, eros non euismod scelerisque, lorem purus molestie ante, non dignissim metus orci ac arcu. Mauris ut tempus ex. Sed est sapien, finibus ut cursus vitae, porta vulputate enim.</p>', 'Public/img/services/service3.jpg', 15),
(4, 'Service Title 4', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vel metus arcu. Quisque efficitur tincidunt erat. Donec suscipit ante eu nisi tincidunt, sed pulvinar metus finibus. Pellentesque volutpat quam nec blandit mollis. Nulla id diam in nulla maximus rhoncus. Pellentesque non magna sed orci viverra bibendum sodales eu erat. In sollicitudin sapien ut enim tempor fermentum. Integer venenatis id metus a accumsan. Donec ut congue augue, vel sagittis sapien. Fusce venenatis nisl elit, ut venenatis ante pretium nec. Donec pretium ut leo ut faucibus.</p>\r\n\r\n<p>Aenean consequat viverra venenatis. Cras vitae congue tellus, in sodales magna. Morbi elementum sed tellus quis varius. Quisque feugiat finibus pharetra. In pretium eu velit ut pretium. Pellentesque aliquam eu metus non porttitor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed egestas lacus quis dapibus placerat. Nullam et mollis justo. Duis mattis bibendum ultricies. Maecenas eget ex rhoncus, facilisis nulla ullamcorper, tempus arcu. Aenean cursus id sapien nec dignissim. Praesent vulputate euismod commodo. Mauris fermentum, turpis ut ultrices luctus, risus sapien pharetra augue, eu elementum dui justo quis nisl. Proin sagittis erat ac commodo consequat.</p>\r\n\r\n<p>Vestibulum viverra justo magna, sed dignissim est aliquam at. Phasellus in mi vel risus tincidunt bibendum nec quis libero. Integer id tortor dolor. Suspendisse consectetur id metus eget molestie. Cras sagittis, sapien ut pharetra mattis, nisl augue pharetra leo, eu consectetur orci metus vitae arcu. Integer in auctor orci. Mauris sit amet lacus eu eros volutpat gravida et a nulla. Aenean ex sem, fermentum ac tortor vitae, finibus tincidunt mi. Cras fringilla, eros non euismod scelerisque, lorem purus molestie ante, non dignissim metus orci ac arcu. Mauris ut tempus ex. Sed est sapien, finibus ut cursus vitae, porta vulputate enim.</p>', 'Public/img/services/service4.jpg', 7),
(5, 'Service Title 5', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vel metus arcu. Quisque efficitur tincidunt erat. Donec suscipit ante eu nisi tincidunt, sed pulvinar metus finibus. Pellentesque volutpat quam nec blandit mollis. Nulla id diam in nulla maximus rhoncus. Pellentesque non magna sed orci viverra bibendum sodales eu erat. In sollicitudin sapien ut enim tempor fermentum. Integer venenatis id metus a accumsan. Donec ut congue augue, vel sagittis sapien. Fusce venenatis nisl elit, ut venenatis ante pretium nec. Donec pretium ut leo ut faucibus.</p>\r\n\r\n<p>Aenean consequat viverra venenatis. Cras vitae congue tellus, in sodales magna. Morbi elementum sed tellus quis varius. Quisque feugiat finibus pharetra. In pretium eu velit ut pretium. Pellentesque aliquam eu metus non porttitor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed egestas lacus quis dapibus placerat. Nullam et mollis justo. Duis mattis bibendum ultricies. Maecenas eget ex rhoncus, facilisis nulla ullamcorper, tempus arcu. Aenean cursus id sapien nec dignissim. Praesent vulputate euismod commodo. Mauris fermentum, turpis ut ultrices luctus, risus sapien pharetra augue, eu elementum dui justo quis nisl. Proin sagittis erat ac commodo consequat.</p>\r\n\r\n<p>Vestibulum viverra justo magna, sed dignissim est aliquam at. Phasellus in mi vel risus tincidunt bibendum nec quis libero. Integer id tortor dolor. Suspendisse consectetur id metus eget molestie. Cras sagittis, sapien ut pharetra mattis, nisl augue pharetra leo, eu consectetur orci metus vitae arcu. Integer in auctor orci. Mauris sit amet lacus eu eros volutpat gravida et a nulla. Aenean ex sem, fermentum ac tortor vitae, finibus tincidunt mi. Cras fringilla, eros non euismod scelerisque, lorem purus molestie ante, non dignissim metus orci ac arcu. Mauris ut tempus ex. Sed est sapien, finibus ut cursus vitae, porta vulputate enim.</p>', 'Public/img/services/service5.jpg', 9);

CREATE TABLE `settings` (
  `company` varchar(100) NOT NULL,
  `address` varchar(250) NOT NULL,
  `phone` varchar(20) NOT NULL,
  `email` varchar(100) NOT NULL,
  `map` varchar(250) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `settings` (`company`, `address`, `phone`, `email`, `map`) VALUES
('PHP App Development Framework', '986 Shinn Street, NY 10022, New York, USA', '917-686-5154', 'fake@sunhill.tech', 'https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d24153.08739439058!2d-73.888969!3d40.824978!3m2!1i1024!2i768!4f13.1!5e0!3m2!1str!2str!4v1659479338214!5m2!1str!2str');